FROM php:8.2-cli

WORKDIR /app

RUN apt-get update && apt-get install -y \
    git \
    unzip \
    libzip-dev \
    libpq-dev \
    && docker-php-ext-install zip pdo pdo_pgsql

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

COPY . .

RUN composer install --no-dev --optimize-autoloader
RUN php artisan migrate --force

RUN chmod -R 775 storage bootstrap/cache

RUN php artisan config:clear \
 && php artisan route:clear \
 && php artisan config:cache

EXPOSE 10000

CMD php artisan serve --host=0.0.0.0 --port=10000